language: node_js
sudo: false
node_js:
  - 10
install:
  - npm install
script:
  - npm run lint
deploy:
  provider: heroku
  api_key: 
    secure: $HEROKU_KEY
  on:
    all_branches: true
# services:
#   - postgresql
# before_script:
#   - echo $DB_USER
#   -  psql -c "CREATE DATABASE $TEST_DB_DATABASE;" -U postgres
#   - psql -c "CREATE USER root WITH PASSWORD 'root';" -U postgres
#   - cp config/database.travis.yml config/database.yml
